
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = '1550B1FC66A8CB9611308F09E20AE0C8'
    
_lr_action_items = {'TIMES':([5,6,7,12,13,14,15,],[10,-8,-7,10,10,-5,-6,]),'DIVIDE':([5,6,7,12,13,14,15,],[11,-8,-7,11,11,-5,-6,]),'NAME':([0,],[1,]),'$end':([2,4,5,6,7,12,13,14,15,],[0,-1,-4,-8,-7,-3,-2,-5,-6,]),'PLUS':([4,5,6,7,12,13,14,15,],[9,-4,-8,-7,-3,-2,-5,-6,]),'EQUALS':([1,],[3,]),'MINUS':([4,5,6,7,12,13,14,15,],[8,-4,-8,-7,-3,-2,-5,-6,]),'NUMBER':([3,8,9,10,11,],[6,6,6,6,6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([3,],[4,]),'factor':([3,8,9,10,11,],[7,7,7,14,15,]),'term':([3,8,9,],[5,12,13,]),'assign':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> NAME EQUALS expr','assign',3,'p_assign','sample_parser.py',5),
  ('expr -> expr PLUS term','expr',3,'p_expr','sample_parser.py',7),
  ('expr -> expr MINUS term','expr',3,'p_expr','sample_parser.py',8),
  ('expr -> term','expr',1,'p_expr','sample_parser.py',9),
  ('term -> term TIMES factor','term',3,'p_term','sample_parser.py',11),
  ('term -> term DIVIDE factor','term',3,'p_term','sample_parser.py',12),
  ('term -> factor','term',1,'p_term','sample_parser.py',13),
  ('factor -> NUMBER','factor',1,'p_factor','sample_parser.py',15),
]
