
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = '8AC72692316468D9DA70925C2579A2D2'
    
_lr_action_items = {'SLASH':([2,3,6,11,16,17,18,],[-9,8,8,-8,8,-11,-10,]),'REGEX':([0,5,8,9,],[2,2,2,2,]),'TILDE':([2,3,6,11,16,17,18,],[-9,5,5,-8,5,-11,-10,]),'$end':([1,2,3,7,10,11,12,14,15,20,],[0,-9,-2,-4,-1,-8,-7,-5,-6,-3,]),'AND':([2,3,7,10,11,12,13,14,15,20,],[-9,-2,-4,-1,-8,-7,18,-5,-6,-3,]),'EQUALS':([2,],[4,]),'LPAREN':([2,3,6,11,16,17,18,],[-9,6,6,-8,6,-11,-10,]),'DOUBLE_SLASH':([2,3,6,11,16,17,18,],[-9,9,9,-8,9,-11,-10,]),'VAR':([4,],[11,]),'OR':([2,3,7,10,11,12,13,14,15,20,],[-9,-2,-4,-1,-8,-7,17,-5,-6,-3,]),'RPAREN':([2,3,7,10,11,12,14,15,19,20,],[-9,-2,-4,-1,-8,-7,-5,-6,20,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'treePattern':([0,5,8,9,],[1,12,14,15,]),'binop':([13,],[16,]),'relation':([3,6,16,],[7,7,7,]),'dirItem':([0,5,8,9,],[3,3,3,3,]),'expression':([3,6,16,],[10,13,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> treePattern","S'",1,None,None,None),
  ('treePattern -> dirItem expression','treePattern',2,'p_treePattern','ir.py',44),
  ('treePattern -> dirItem','treePattern',1,'p_treePattern','ir.py',45),
  ('expression -> LPAREN expression binop expression RPAREN','expression',5,'p_expression_binary','ir.py',49),
  ('expression -> relation','expression',1,'p_expression_leaf','ir.py',53),
  ('relation -> SLASH treePattern','relation',2,'p_relation','ir.py',57),
  ('relation -> DOUBLE_SLASH treePattern','relation',2,'p_relation','ir.py',58),
  ('relation -> TILDE treePattern','relation',2,'p_relation','ir.py',59),
  ('dirItem -> REGEX EQUALS VAR','dirItem',3,'p_dirItem','ir.py',63),
  ('dirItem -> REGEX','dirItem',1,'p_dirItem','ir.py',64),
  ('binop -> AND','binop',1,'p_binop','ir.py',68),
  ('binop -> OR','binop',1,'p_binop','ir.py',69),
]
